import Head from 'next/head'
import Main from "../components/Main";
import About from "../components/About";
import Skills from "../components/Skills";
import Projects from "../components/Projects";
import Contact from "../components/Contact";
import { useSelector } from 'react-redux'


export default function Home() {
    const langState = useSelector((state) => state.lang.lang);
    return (
        <div>
            <Head>
                <title>{langState === 'gb' ? "Kevin MAS | Web Developer" : "Kevin MAS | Développeur web"}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Main />
            <About />
            <Skills />
            <Projects />
            <Contact />
        </div>
    )
}
